import { Card } from "./card";

export const ProposalCardList: Card[] = [
    new Card('RELIGIOSITY: Religious Feast', 'INSTANT: +8 Religiosity, +2 Peasant Satisfaction, -8 Money', false),
    new Card('FOOD STOCKPILE: Industrial Revolution', 'INSTANT: -5 Peasant Happiness. ONGOING: each turn flip a coin. On heads, +1 Food Stockpile', true),
    new Card('FOOD STOCKPILE: Rationing', 'ONGOING: Each turn +1 Food Stockpile and flip a coin. On heads, -1 Peasant Happiness. On tails -1 Military Advantage', true),
    new Card('FOOD STOCKPILE: Rationing', 'ONGOING: Each turn +1 Food Stockpile and flip a coin. On heads, -1 Peasant Happiness. On tails -1 Military Advantage', true),
    new Card('FOOD STOCKPILE: Rationing', 'ONGOING: Each turn +1 Food Stockpile and flip a coin. On heads, -1 Peasant Happiness. On tails -1 Military Advantage', true),
    new Card('LEGAL INTEGRITY: Repeal', 'INSTANT: Repeal an ongoing card and +2 Legal Integrity', false),
    new Card('LEGAL INTEGRITY: Repeal', 'INSTANT: Repeal an ongoing card and +2 Legal Integrity', false),
    new Card('LEGAL INTEGRITY: Repeal', 'INSTANT: Repeal an ongoing card and +2 Legal Integrity', false),
    new Card('LEGAL INTEGRITY: Repeal', 'INSTANT: Repeal an ongoing card and +2 Legal Integrity', false),
    new Card('MILITARY ADVANTAGE: Siege', 'INSTANT: +6 Military Advantage, -2 Foreign Relations. ONGOING: Each turn -1 Money, -1 Food Stockpile, and roll 1d6. On 6, +4 Noble Satifaction, +4 Money', true),
    new Card('MILITARY ADVANTAGE: Peasant Draft', 'INSTANT: +3 Military Advantage, -2 Peasant Satisfaction', false),
    new Card('MILITARY ADVANTAGE: Knights', 'INSTANT: +4 Military Advantage, -3 Money', false),
    new Card('MILITARY ADVANTAGE: Battle', 'INSTANT: -2 Foreign Relations and add current Military Advantage minus 2d6 to Military Advantage', false),
    new Card('MILITARY ADVANTAGE: Battle', 'INSTANT: -2 Foreign Relations and add current Military Advantage minus 2d6 to Military Advantage', false),
    new Card('MILITARY ADVANTAGE: Battle', 'INSTANT: -2 Foreign Relations and add current Military Advantage minus 2d6 to Military Advantage', false),
    new Card('NOBLE SATISFACTION: Noble Immunity', 'INSTANT: +4 Noble Satisfaction, -1 Peasant Satisfaction, -2 Legal Integrity', false),
    new Card('PEASANT SATISFACTION: Taverns', 'INSTANT: +5 Peasant Satisfaction, -1 Military Advantage, -1 Foreign Relations, -2 Religiosity', false),
    new Card('MONEY: Investment', 'INSTANT: -2 Money, -2 Noble Satisfaction. ONGOING: each turn flip a coin. On heads, +1 Money', true),
    new Card('MONEY: Taxes', 'INSTANT: +5 Money, -2 Noble Satisfaction, -2 Peasant Satisfaction', false),
    new Card('RELIGIOSITY: Enforce Moral Law', 'INSTANT: +6 Religiosity, +1 Legal Integrity, -2 Noble Satisfaction, -2 Peasant Satisfaction', false),
    new Card('PEASANT SATISFACTION: Relax Moral Law', 'INSTANT: +3 Peasant Satisfaction, +2 Noble Satisfaction, -1 Legal Integrity, -4 Religiosity', false),
    new Card('NOBLE SATISFACTION: Loopholes', 'INSTANT: Add the number of active ongoing cards to Noble Satisfaction, -3 Legal Integrity', false),
    new Card('MONEY: Cutbacks', 'INSTANT: +4 Money, +2 Food Stockpile, -1 Legal Integrity, -3 Military Advantage', false),
    new Card('PEASANT SATISFACTION: Peasant Rights', 'INSTANT: +3 Peasant Satisfaction, -3 Noble Satisfaction', false),
    new Card('FOREIGN RELATIONS: Disarment', 'INSTANT: +4 Food Stockpile, +1 Peasant Satisfaction, -3 Military Advantage', false),
    new Card('FOREIGN RELATIONS: Trade Negotation', 'INSTANT: +3 Food Stockpile, +1 Money, -2 Foreign Relations', false),
    new Card('PEASANT SATISFACTION: Draft Dodging', 'INSTANT: +3 Peasant Satisfaction, -2 Military Advantage', false),
    new Card('MONEY: Bribed Bishops', 'INSTANT: +6 Money, -1 Legal Integrity, -4 Religiosity', false),
    new Card('LEGAL INTEGRITY: Increase law enforcement', 'INSTANT: +5 Legal Integrity, -4 Military Advantage', false),
    new Card('FOOD STOCKPILE: Food restrictions', 'INSTANT: +4 Foreign Relations, -3 Noble Satisfaction', false),
    new Card('PEASANT SATISFACTION: Handouts', 'INSTANT: +3 Peasant Satisfaction, -1 Foreign Relations', false),
    new Card('FOREIGN RELATIONS: Peace treaty', 'INSTANT: +3 Food Stockpile, -2 Military Advantage', false),
    new Card('NOBLE SATISFACTION: Raises for officers', 'INSTANT: +3 Noble Satisfaction, +2 Military Advantage, -2 Money', false),
    new Card('MONEY: Progressive Tax', 'INSTANT: +4 Money, -3 Noble Satisfaction', false),
    new Card('NOBLE SATISFACTION: Loosen draft restriction', 'INSTANT: +2 Noble Satisfaction, -1 Military Advantage', false),
    new Card('FOOD STOCKPILE: Import food', 'INSTANT: +3 Foreign Relations, +1 Food Stockpile, -2 Money', false),
    new Card('FOREIGN RELATIONS: International Feast', 'INSTANT: +2 Food Stockpile, +1 Legal Integrity, -2 Foreign Relations', false),
    new Card('PEASANT SATISFACTION: National Pride', 'INSTANT: +2 Peasant Satisfaction, -1 Food Stockpile', false),
    new Card('MONEY: Regressive Tax', 'INSTANT: +4 Money, -3 Peasant Satisfaction', false),
    new Card('MILITARY ADVANTAGE: Quartering Soldiers', 'INSTANT: +2 Military Advantage, -1 Peasant Satisfaction', false),
    new Card('PEASANT SATISFACTION: Circus', 'INSTANT: +5 Peasant Satisfaction, -3 Religiosity', false),
    new Card('RELIGIOSITY: Faked Miracle', 'INSTANT: +8 Religiosity. ONGOING: every turn roll 1d6. On 1, -12 Religiosity and repeal this card', true),
    new Card('MONEY: Hidden Stash', 'INSTANT: +4 Money. ONGOING: Each turn roll 1d6. On 1, -4 Money, +3 Noble Satisfaction, +1 Peasant Satisfaction and repeal this card', true),
    new Card('FOREIGN RELATIONS: Secret Alliance', 'INSTANT: +4 Foreign Relations. ONGOING: Each turn roll 1d6. On 1, -4 Foreign Relations, +3 Military Advantage and repeal this card', true),
    new Card('FOOD STOCKPILE: Increased work hours', 'INSTANT: -4 Peasant Satisfaction. ONGOING: Each turn +1 Food Stockpile', true),
    new Card('NOBLE SATISFACTION: Corrupt Judges', 'INSTANT: +4 Noble Satisfaction, +1 Money, -4 Legal Integrity', false),
    new Card('LEGAL INTEGRITY: Trial By Jury', 'INSTANT: +3 Legal Integrity, +1 Peasant Satisfaction, -3 Noble Satisfaction', false),
    new Card('LEGAL INTEGRITY: Pro Bono Lawyers', 'INSTANT: +3 Legal Integrity, -2 Money', false),
    new Card('PEASANT SATISFACTION: Stimulus', 'INSTANT: +4 Peasant Satisfaction, -3 Money', false),
    new Card('MONEY: Privateer', 'INSTANT: +3 Money, +1 Military Advantage, -1 Food Stockpile, -2 Foreign Relations', false),
    new Card('MONEY: Coin Clipping', 'INSTANT: +4 Money. ONGOING: Each turn roll 1d6. On 1, -4 Money, -2 Noble Satisfaction, -1 Foreign Relations and repeal this card', true),
    new Card('FOREIGN RELATIONS: Pay Tribute', 'INSTANT: +4 Food Stockpile, -3 Money', false),
    new Card('MONEY: Collect Taxes', 'INSTANT: +3 Money, -1 Noble Satisfaction, -1 Peasant Satisfaction', false),
    new Card('MONEY: Collect Taxes', 'INSTANT: +3 Money, -1 Noble Satisfaction, -1 Peasant Satisfaction', false),
    new Card('MONEY: Collect Taxes', 'INSTANT: +3 Money, -1 Noble Satisfaction, -1 Peasant Satisfaction', false),
    new Card('PEASANT SATISFACTION: Education', 'INSTANT: +5 Peasant Satisfaction, -4 Money', false),
    new Card('PEASANT SATISFACTION: Printing Press', 'INSTANT: +3 Peasant Satisfaction, +2 Legal Integrity, -4 Money', false),
    new Card('MILITARY ADVANTAGE: Sun Raft', 'INSTANT: +3 Military Advantage, +2 Noble Satisfaction, +1 Religiosity, -1 Food Stockpile, -4 Money', false),
    new Card('PEASANT SATISFACTION: Feast', 'INSTANT: +3 Peasant Satisfaction, -2 Foreign Relations', false),
    new Card('PEASANT SATISFACTION: Feast', 'INSTANT: +3 Peasant Satisfaction, -2 Foreign Relations', false),
    new Card('PEASANT SATISFACTION: Feast', 'INSTANT: +3 Peasant Satisfaction, -2 Foreign Relations', false),
    new Card('MILITARY ADVANTAGE: Martial Law', 'INSTANT: +4 Military Advantage, -2 Legal Integrity, -2 Peasant Satisfaction', false),
    new Card('NOBLE SATISFACTION: Populism', 'INSTANT: +3 Peasant Satisfaction, -2 Noble Satisfaction', false),
    new Card('NOBLE SATISFACTION: Serfdom', 'INSTANT: +3 Noble Satisfaction, +2 Money, +1 Foreign Relations, -5 Peasant Satisfaction', false),
    new Card('MILITARY ADVANTAGE: Build Roads', 'INSTANT: +3 Military Advantage, +1 Noble Satisfaction, +1 Peasant Satisfaction, -2 Money, -2 Foreign Relations', false),
    new Card('RELIGIOSITY: Enforce Tithing', 'INSTANT: +7 Religiosity, -5 Peasant Satisfaction', false),
    new Card('LEGAL INTEGRITY: Separation of Church and State', 'INSTANT: +4 Legal Integrity, -3 Religiosity', false),
    new Card('NOBLE SATISFACTION: Private Army', 'INSTANT: +4 Noble Satisfaction, +1 Money, -4 Military Advantage', false),
    new Card('FOREIGN RELATIONS: Idols', 'INSTANT: +3 Food Stockpile, -2 Religiosity', false),
    new Card('NOBLE SATISFACTION: News Coffin', 'INSTANT: +3 Noble Satisfaction, +1 Money, -1 Military Advantage, -2 Legal Integrity', false),
    new Card('LEGAL INTEGRITY: Citizenship Requirements', 'INSTANT: +4 Legal Integrity, -3 Food Stockpile', false),
    new Card('FOOD STOCKPILE: Ban of Feasts', 'INSTANT: +4 Food Stockpile. ONGOING: While this card is active, no cards with the word "feast" in their name may be enacted', true),
    new Card('FOOD STOCKPILE: Seal the Storehouses', 'INSTANT: +1 Food Stockpile. ONGOING: While this card is active, no Food Stockpile cards may be enacted', true),
    new Card('MILITARY ADVANTAGE: Military Hiring Freeze', 'INSTANT: +1 Military Advantage. ONGOING: While this card is active, no Military Advantage cards may be enacted', true),
    new Card('MONEY: Treasury Freeze', 'INSTANT: +1 Money. ONGOING: While this card is active, no Money cards may be enacted', true),
    new Card('RELIGIOSITY: Church Lockdown', 'INSTANT: +1 Religiosity. ONGOING: While this card is active, no Religiosity cards may be enacted', true),
    new Card('LEGAL INTEGRITY: Court Shutdown', 'INSTANT: +1 Legal Integrity. ONGOING: While this card is active, no Legal Integrity cards may be enacted except to repeal this card', true),
    new Card('NOBLE SATISFACTION: Gluttony Ban', 'INSTANT: +1 Noble Satisfaction. ONGOING: While this card is active, no Noble Satisfaction cards may be enacted', true),
    new Card('FOOD STOCKPILE: Halt External Communication', 'INSTANT: +1 Foreign Relations. ONGOING: While this card is active, no Foreign Relations cards may be enacted', true),
    new Card('PEASANT SATISFACTION: Closed Town Square', 'INSTANT: +1 Peasant Satisfaction. ONGOING: While this card is active, no Food Peasant Satisfaction may be enacted', true),
]